### ISSUE TITLE
Combine effords.

### ISSUE THREAD

**Issue by ypid** [martin-v/ansible-sshpreluks#1]
Hi @martin-v and @0x46616c6b

It seems you guys have created role with similar goals than [ypid.cryptsetup_remote_unlock](https://github.com/ypid/ansible-cryptsetup_remote_unlock). I think we could work together also because all three of us seem to target the same distribution (Debian GNU/Linux). I might rework my role someday in the future and would try to combine features that it is missing and then migrate the role to the [DebOps project](http://debops.org/). Let me know what you think. Also, where you aware of the already existing roles when you wrote your roles?

**Comment by martin-v** [comment]
Hi ypid,

I'm fine with working together. 

I think the biggest problem is the etckeeper support branch. I want to use etckeeper on my machines and ansible should make small useful commits. A friend has written a [ansible-etckeeper](https://github.com/fxkr/ansible-etckeeper) module. It works fine, but I'm not really happy with the amount of code you need to maintain.

I compared our roles with each other:
- The differences in the installed packages are all normally installed by default on debian (busybox, initramfs-tools,  cryptsetup). I think busybox, initramfs-tools is the correct combination.
- GRUB_TIMEOUT is not really a in scope, but is a nice-to-have feature.
- I had the issues with missing the network driver on my NAS, so I need the "Add network driver to initramfs modules" part.
- To authorize the ssh session it is better to simply add a authorized_key 

Feel free to copy parts of my role, I'm also fine if you put it under AGPL. 
When you finished the refactoring a say a word and I will make some tests.

Best Regards
 Martin

**Comment by ypid** [comment]
Thanks for your feedback.

I also like etckeeper ([ref](https://github.com/debops-contrib/ansible-etckeeper)) and the module you liked to looks interesting but I would not use the etckeeper module inside of roles because other people might not use etckeeper. I usually rely on the daily autocommits of etckeeper. I don’t really need useful commit messages. The automatic messages from etckeeper are reasonable enough for me. I do almost all changes to `/etc` via Ansible anyway so manual intervention is not intended in my setup. When someone really wants to do that the answer of the DebOps project for this is that it can be done in [pre_tasks](https://github.com/debops/ansible-auth/blob/master/tasks/main.yml#L3-L4) and post_tasks plays using the [task_src lookup plugins/](https://github.com/debops/debops-playbooks/blob/master/playbooks/lookup_plugins/task_src.py).

> Feel free to copy parts of my role, I'm also fine if you put it under AGPL.

Thanks very much! But as this role would be intended for the DebOps project, I would put it under the GPL-3.0 see [discussion](https://github.com/debops/ansible-cryptsetup/pull/1).

> I think busybox, initramfs-tools is the correct combination.

I think it should be: :wink:

``` YAML
- 'dropbear'
- 'busybox'
- 'initramfs-tools'
```

> GRUB_TIMEOUT

Still legacy code. [debops.grub](https://github.com/debops/ansible-grub) does a much better job here. Basically, my role this role was one of the first Ansible roles I wrote. It could need some rework.

> To authorize the ssh session it is better to simply add a authorized_key 

I will look into this.

All right. Lets see when I find the time. Probably not within a month.

**Comment by martin-v** [comment]
> > Feel free to copy parts of my role, I'm also fine if you put it under AGPL.
> 
> Thanks very much! But as this role would be intended for the DebOps project, I would put it under the 
> GPL-3.0 see discussion.

This is also fine for me.

**Comment by ypid** [comment]
Done: https://github.com/debops-contrib/ansible-dropbear_initramfs :)
